language: haskell

script:
  - cabal configure --enable-tests && cabal test

before_install:
  - git clone https://github.com/alpmestan/taggy.git
  - cabal sandbox init
  - cabal sandbox add-source taggy/
  
notifications:
  email:
      - alpmestan@gmail.com
      - vi@zalora.com
  irc: "irc.freenode.org#haskell-math"
